name: depolarized-holography
channels:
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - abseil-cpp=20211102.0
  - absl-py=1.1.0
  - aiohttp=3.8.1
  - aiosignal=1.2.0
  - aom=3.3.0
  - asttokens=2.0.5
  - async-timeout=4.0.2
  - attrs=21.4.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - blas=2.115
  - blas-devel=3.9.0
  - blinker=1.4
  - blosc=1.21.1
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - c-blosc2=2.2.0
  - ca-certificates=2022.9.24
  - certifi=2022.9.24
  - cffi=1.15.1
  - cfitsio=4.1.0
  - charls=2.3.4
  - charset-normalizer=2.1.0
  - click=8.1.3
  - cloudpickle=2.1.0
  - colorama=0.4.5
  - configargparse=1.4
  - cryptography=37.0.4
  - cudatoolkit=11.3.1
  - cycler=0.11.0
  - cytoolz=0.11.2
  - dask-core=2022.6.1
  - debugpy=1.6.0
  - decorator=5.1.1
  - entrypoints=0.4
  - executing=0.8.3
  - fonttools=4.34.4
  - freeglut=3.2.2
  - freetype=2.10.4
  - frozenlist=1.3.0
  - fsspec=2022.5.0
  - future=0.18.2
  - giflib=5.2.1
  - google-auth-oauthlib=0.4.1
  - grpc-cpp=1.47.0
  - grpcio=1.47.0
  - icu=68.2
  - idna=3.3
  - imagecodecs=2022.2.22
  - imageio=2.19.3
  - importlib-metadata=4.11.4
  - intel-openmp=2022.1.0
  - ipykernel=6.15.0
  - ipython=8.4.0
  - jasper=2.0.33
  - jedi=0.18.1
  - jpeg=9e
  - jupyter_client=7.3.4
  - jupyter_core=4.10.0
  - jxrlib=1.1
  - kiwisolver=1.4.3
  - krb5=1.19.3
  - lcms2=2.12
  - lerc=3.0
  - libaec=1.0.6
  - libavif=0.10.1
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libclang=11.1.0
  - libcurl=7.83.1
  - libdeflate=1.12
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libopencv=4.5.5
  - libpng=1.6.37
  - libprotobuf=3.20.1
  - libsodium=1.0.18
  - libssh2=1.10.0
  - libtiff=4.4.0
  - libuv=1.43.0
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - libxcb=1.13
  - libzlib=1.2.12
  - libzopfli=1.0.3
  - locket=1.0.0
  - lz4-c=1.9.3
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - markdown=3.3.7
  - matplotlib=3.5.1
  - matplotlib-base=3.5.1
  - matplotlib-inline=0.1.3
  - mkl=2022.1.0
  - mkl-devel=2022.1.0
  - mkl-include=2022.1.0
  - msys2-conda-epoch=20160418
  - multidict=6.0.2
  - munkres=1.1.4
  - nest-asyncio=1.5.5
  - networkx=2.8.4
  - oauthlib=3.2.0
  - opencv=4.5.5
  - openjpeg=2.4.0
  - openssl=1.1.1q
  - packaging=21.3
  - parso=0.8.3
  - partd=1.2.0
  - pickleshare=0.7.5
  - pillow=9.2.0
  - pip=22.1.2
  - prompt-toolkit=3.0.30
  - psutil=5.9.1
  - pthread-stubs=0.4
  - pure_eval=0.2.2
  - py-opencv=4.5.5
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycparser=2.21
  - pygments=2.12.0
  - pyjwt=2.4.0
  - pyopenssl=22.0.0
  - pyparsing=3.0.9
  - pyqt=5.12.3
  - pysocks=1.7.1
  - python=3.9.12
  - python-dateutil=2.8.2
  - python_abi=3.9
  - pytorch=1.12.0
  - pytorch-lightning=1.5.8
  - pytorch-mutex=1.0
  - pyu2f=0.1.5
  - pywavelets=1.3.0
  - pywin32=303
  - pyyaml=6.0
  - pyzmq=23.2.0
  - qt=5.12.9
  - re2=2022.06.01
  - requests=2.28.1
  - requests-oauthlib=1.3.1
  - rsa=4.8
  - scikit-image=0.19.2
  - scipy=1.8.1
  - screeninfo=0.7
  - setuptools=63.1.0
  - six=1.16.0
  - snappy=1.1.9
  - sqlite=3.39.0
  - stack_data=0.3.0
  - tbb=2021.5.0
  - tensorboard-data-server=0.6.0
  - tensorboard-plugin-wit=1.8.1
  - tifffile=2022.5.4
  - tk=8.6.12
  - toolz=0.11.2
  - torchaudio=0.12.0
  - torchmetrics=0.10.0
  - torchvision=0.13.0
  - tornado=6.2
  - tqdm=4.64.0
  - traitlets=5.3.0
  - typing-extensions=4.3.0
  - typing_extensions=4.3.0
  - tzdata=2022a
  - ucrt=10.0.20348.0
  - unicodedata2=14.0.0
  - urllib3=1.26.10
  - vc=14.2
  - vs2015_runtime=14.29.30037
  - wcwidth=0.2.5
  - werkzeug=2.1.2
  - wheel=0.37.1
  - win_inet_pton=1.1.0
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.5
  - yaml=0.2.5
  - yarl=1.7.2
  - zeromq=4.3.4
  - zfp=0.5.5
  - zipp=3.8.0
  - zlib=1.2.12
  - zlib-ng=2.0.6
  - zstd=1.5.2
  - pip:
      - aotools==1.0.6
      - cachetools==4.2.4
      - google-auth==1.35.0
      - iqa-pytorch==0.1
      - llvmlite==0.39.0
      - mpmath==1.2.1
      - numba==0.56.0
      - numpy==1.22.4
      - pandas==1.4.3
      - pip-chill==1.0.1
      - protobuf==3.19.6
      - pydeprecate==0.3.2
      - pyqt5-sip==4.19.18
      - pyqtchart==5.12
      - pyqtwebengine==5.12.1
      - pytz==2022.1
      - tensorboard==2.10.1
      - torch-dct==0.1.5
      - torch-tb-profiler==0.4.0
